// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhap1.Data;

#nullable disable

namespace Nhap1.Migrations
{
    [DbContext(typeof(MvcMovieDbContext))]
    partial class MvcMovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Nhap1.Models.PhongBan", b =>
                {
                    b.Property<string>("MaPB")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenPB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaPB");

                    b.ToTable("PhongBan");
                });
#pragma warning restore 612, 618
        }
    }
}
